#!/bin/bash
mkdir rootfs

FSDIR="$(readlink -f ./rootfs)"
docker run --rm --privileged -v $FSDIR:/build s8sg/root-fs-builder:latest

ROOTFSDIR="$(readlink -f ./rootfs/rootfs)"
echo "Root filesystem created as: $ROOTFSDIR"
