#!/bin/bash

# run this container like so
# docker run --rm --privileged -v /your/local/dir/path:/build firecracker-builder

set -ex

dd if=/dev/zero of=/tmp/rootfs bs=1M count=10
mkfs.ext4 /tmp/rootfs

mkdir /tmp/tmp
# mknod /dev/loop0 b 7 0 
mount /tmp/rootfs /tmp/tmp -o loop

tar xzf /tmp/alpine-minirootfs-3.8.1-x86_64.tar.gz -C /tmp/tmp

cp -r  /tmp/overlay/* /tmp/tmp/

#cat > /tmp/tmp/prepare.sh <<EOF
#passwd root -d root
#apk add -u openrc ca-certificates
#exit 
#EOF

#chroot /tmp/tmp/ /bin/sh /prepare.sh

# rm /tmp/tmp/prepare.sh 

umount /tmp/tmp

cp /tmp/rootfs /build/
